//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhomB4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderProes = new HashSet<OrderPro>();
        }
        [Key]
        public int IDCus { get; set; }
        [Required]
        public string NameCus { get; set; }
        [Required]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Number is required")]
        public string PhoneCus { get; set; }
        [Required]
          [RegularExpression(@"^[a-zA-Z0-9_.+-]+@gmail\.com$", ErrorMessage = "Phải có @gmail.com")]
        public string EmailCus { get; set; }
        [Required]
        [RegularExpression(@"^[A-Za-z 0-9]*$",ErrorMessage = "Special characters cannot be used")]
        [MinLength(4,ErrorMessage = "Must be more than 4 characters")]
        public string UserName { get; set; }
        [Required]
        [MinLength(4, ErrorMessage = "Must be more than 4 characters")]
        public string Password { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderProes { get; set; }
    }
}
